export const sampleData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    age: 20,
    gender: "Male",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
    phone: "555-1234",
    email: "john.doe@example.com",
    course: "Computer Science",
    year: "Sophomore",
    gpa: 3.5,
    advisor: "Dr. Smith",
    enrolled: true,
    credits: 30,
    minor: "Math",
    clubs: ["Chess Club", "Robotics Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    age: 21,
    gender: "Female",
    address: "456 Elm St",
    city: "Othertown",
    state: "NY",
    zip: "67890",
    phone: "555-5678",
    email: "jane.smith@example.com",
    course: "Biology",
    year: "Junior",
    gpa: 3.8,
    advisor: "Dr. Johnson",
    enrolled: true,
    credits: 60,
    minor: "Chemistry",
    clubs: ["Biology Club", "Swim Team"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    age: 19,
    gender: "Female",
    address: "789 Maple St",
    city: "Smalltown",
    state: "TX",
    zip: "23456",
    phone: "555-8765",
    email: "alice.johnson@example.com",
    course: "Mathematics",
    year: "Freshman",
    gpa: 3.9,
    advisor: "Dr. Brown",
    enrolled: true,
    credits: 15,
    minor: "Physics",
    clubs: ["Math Club", "Tennis Team"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Williams",
    age: 22,
    gender: "Male",
    address: "101 Pine St",
    city: "Largetown",
    state: "FL",
    zip: "34567",
    phone: "555-3456",
    email: "bob.williams@example.com",
    course: "History",
    year: "Senior",
    gpa: 3.4,
    advisor: "Dr. White",
    enrolled: true,
    credits: 90,
    minor: "Political Science",
    clubs: ["History Club", "Debate Team"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 5,
    firstName: "Charlie",
    lastName: "Brown",
    age: 20,
    gender: "Male",
    address: "202 Oak St",
    city: "Oldtown",
    state: "OH",
    zip: "45678",
    phone: "555-6789",
    email: "charlie.brown@example.com",
    course: "Engineering",
    year: "Sophomore",
    gpa: 3.6,
    advisor: "Dr. Green",
    enrolled: true,
    credits: 45,
    minor: "Computer Science",
    clubs: ["Engineering Club", "Basketball Team"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 6,
    firstName: "David",
    lastName: "Jones",
    age: 23,
    gender: "Male",
    address: "303 Birch St",
    city: "Newtown",
    state: "IL",
    zip: "56789",
    phone: "555-7890",
    email: "david.jones@example.com",
    course: "Physics",
    year: "Senior",
    gpa: 3.7,
    advisor: "Dr. Black",
    enrolled: true,
    credits: 105,
    minor: "Astronomy",
    clubs: ["Physics Club", "Soccer Team"],
    scholarship: true,
    partTime: true,
  },
  {
    id: 7,
    firstName: "Eve",
    lastName: "Davis",
    age: 21,
    gender: "Female",
    address: "404 Cedar St",
    city: "Middletown",
    state: "GA",
    zip: "67890",
    phone: "555-8901",
    email: "eve.davis@example.com",
    course: "Chemistry",
    year: "Junior",
    gpa: 3.5,
    advisor: "Dr. Gray",
    enrolled: true,
    credits: 75,
    minor: "Biology",
    clubs: ["Chemistry Club", "Volleyball Team"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 8,
    firstName: "Fiona",
    lastName: "Garcia",
    age: 22,
    gender: "Female",
    address: "505 Walnut St",
    city: "Smallcity",
    state: "NJ",
    zip: "78901",
    phone: "555-9012",
    email: "fiona.garcia@example.com",
    course: "Art",
    year: "Senior",
    gpa: 3.8,
    advisor: "Dr. Violet",
    enrolled: true,
    credits: 90,
    minor: "Art History",
    clubs: ["Art Club", "Photography Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 9,
    firstName: "George",
    lastName: "Martinez",
    age: 20,
    gender: "Male",
    address: "606 Chestnut St",
    city: "Bigcity",
    state: "PA",
    zip: "89012",
    phone: "555-0123",
    email: "george.martinez@example.com",
    course: "Business",
    year: "Sophomore",
    gpa: 3.6,
    advisor: "Dr. Gold",
    enrolled: true,
    credits: 45,
    minor: "Economics",
    clubs: ["Business Club", "Finance Club"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 10,
    firstName: "Hannah",
    lastName: "Wilson",
    age: 19,
    gender: "Female",
    address: "707 Poplar St",
    city: "Smalltown",
    state: "WA",
    zip: "90123",
    phone: "555-1234",
    email: "hannah.wilson@example.com",
    course: "English",
    year: "Freshman",
    gpa: 3.7,
    advisor: "Dr. Silver",
    enrolled: true,
    credits: 15,
    minor: "Creative Writing",
    clubs: ["Literature Club", "Drama Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 11,
    firstName: "Ian",
    lastName: "Lopez",
    age: 22,
    gender: "Male",
    address: "808 Spruce St",
    city: "Villagetown",
    state: "OR",
    zip: "01234",
    phone: "555-2345",
    email: "ian.lopez@example.com",
    course: "Psychology",
    year: "Senior",
    gpa: 3.9,
    advisor: "Dr. Bronze",
    enrolled: true,
    credits: 95,
    minor: "Sociology",
    clubs: ["Psychology Club", "Yoga Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 12,
    firstName: "Jack",
    lastName: "Lee",
    age: 21,
    gender: "Male",
    address: "909 Redwood St",
    city: "Townsville",
    state: "AZ",
    zip: "12345",
    phone: "555-3456",
    email: "jack.lee@example.com",
    course: "Philosophy",
    year: "Junior",
    gpa: 3.4,
    advisor: "Dr. Copper",
    enrolled: true,
    credits: 65,
    minor: "Ethics",
    clubs: ["Philosophy Club", "Hiking Club"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 13,
    firstName: "Karen",
    lastName: "Kim",
    age: 23,
    gender: "Female",
    address: "1010 Ash St",
    city: "Citytown",
    state: "NV",
    zip: "23456",
    phone: "555-4567",
    email: "karen.kim@example.com",
    course: "Economics",
    year: "Senior",
    gpa: 3.6,
    advisor: "Dr. Iron",
    enrolled: true,
    credits: 100,
    minor: "Finance",
    clubs: ["Economics Club", "Investment Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 14,
    firstName: "Leo",
    lastName: "Gonzalez",
    age: 20,
    gender: "Male",
    address: "1111 Pine St",
    city: "Metropolis",
    state: "CO",
    zip: "34567",
    phone: "555-5678",
    email: "leo.gonzalez@example.com",
    course: "Music",
    year: "Sophomore",
    gpa: 3.5,
    advisor: "Dr. Steel",
    enrolled: true,
    credits: 40,
    minor: "Theater",
    clubs: ["Music Club", "Band"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 15,
    firstName: "Maria",
    lastName: "Hernandez",
    age: 21,
    gender: "Female",
    address: "1212 Birch St",
    city: "Seaside",
    state: "FL",
    zip: "45678",
    phone: "555-6789",
    email: "maria.hernandez@example.com",
    course: "Nursing",
    year: "Junior",
    gpa: 3.8,
    advisor: "Dr. Tin",
    enrolled: true,
    credits: 75,
    minor: "Health Science",
    clubs: ["Nursing Club", "Health Club"],
    scholarship: true,
    partTime: true,
  },
  {
    id: 16,
    firstName: "Nathan",
    lastName: "Clark",
    age: 22,
    gender: "Male",
    address: "1313 Cedar St",
    city: "Lakeside",
    state: "TX",
    zip: "56789",
    phone: "555-7890",
    email: "nathan.clark@example.com",
    course: "Architecture",
    year: "Senior",
    gpa: 3.6,
    advisor: "Dr. Lead",
    enrolled: true,
    credits: 90,
    minor: "Civil Engineering",
    clubs: ["Architecture Club", "Design Club"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 17,
    firstName: "Olivia",
    lastName: "Martinez",
    age: 20,
    gender: "Female",
    address: "1414 Oak St",
    city: "Mountainview",
    state: "CA",
    zip: "67890",
    phone: "555-8901",
    email: "olivia.martinez@example.com",
    course: "Environmental Science",
    year: "Sophomore",
    gpa: 3.7,
    advisor: "Dr. Zinc",
    enrolled: true,
    credits: 45,
    minor: "Geology",
    clubs: ["Eco Club", "Hiking Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 18,
    firstName: "Paul",
    lastName: "Lewis",
    age: 19,
    gender: "Male",
    address: "1515 Spruce St",
    city: "Rivercity",
    state: "WA",
    zip: "78901",
    phone: "555-9012",
    email: "paul.lewis@example.com",
    course: "Sociology",
    year: "Freshman",
    gpa: 3.5,
    advisor: "Dr. Nickel",
    enrolled: true,
    credits: 15,
    minor: "Anthropology",
    clubs: ["Sociology Club", "Basketball Team"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 19,
    firstName: "Quinn",
    lastName: "Walker",
    age: 21,
    gender: "Female",
    address: "1616 Maple St",
    city: "Hilltown",
    state: "NY",
    zip: "89012",
    phone: "555-0123",
    email: "quinn.walker@example.com",
    course: "Political Science",
    year: "Junior",
    gpa: 3.6,
    advisor: "Dr. Copper",
    enrolled: true,
    credits: 60,
    minor: "History",
    clubs: ["Debate Club", "Model UN"],
    scholarship: true,
    partTime: true,
  },
  {
    id: 20,
    firstName: "Ryan",
    lastName: "Hill",
    age: 22,
    gender: "Male",
    address: "1717 Elm St",
    city: "Springfield",
    state: "IL",
    zip: "90123",
    phone: "555-1234",
    email: "ryan.hill@example.com",
    course: "Engineering",
    year: "Senior",
    gpa: 3.7,
    advisor: "Dr. Gold",
    enrolled: true,
    credits: 105,
    minor: "Computer Science",
    clubs: ["Engineering Club", "Soccer Team"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 21,
    firstName: "Sophia",
    lastName: "Scott",
    age: 19,
    gender: "Female",
    address: "1818 Poplar St",
    city: "Laketown",
    state: "NJ",
    zip: "01234",
    phone: "555-2345",
    email: "sophia.scott@example.com",
    course: "Psychology",
    year: "Freshman",
    gpa: 3.8,
    advisor: "Dr. Silver",
    enrolled: true,
    credits: 20,
    minor: "Criminology",
    clubs: ["Psychology Club", "Swim Team"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 22,
    firstName: "Thomas",
    lastName: "Young",
    age: 20,
    gender: "Male",
    address: "1919 Chestnut St",
    city: "Foreston",
    state: "OR",
    zip: "12345",
    phone: "555-3456",
    email: "thomas.young@example.com",
    course: "Computer Science",
    year: "Sophomore",
    gpa: 3.9,
    advisor: "Dr. Bronze",
    enrolled: true,
    credits: 45,
    minor: "Math",
    clubs: ["Coding Club", "Robotics Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 23,
    firstName: "Uma",
    lastName: "Allen",
    age: 21,
    gender: "Female",
    address: "2020 Walnut St",
    city: "Beachcity",
    state: "AZ",
    zip: "23456",
    phone: "555-4567",
    email: "uma.allen@example.com",
    course: "Marketing",
    year: "Junior",
    gpa: 3.5,
    advisor: "Dr. Copper",
    enrolled: true,
    credits: 60,
    minor: "Business",
    clubs: ["Marketing Club", "Advertising Club"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 24,
    firstName: "Victor",
    lastName: "Harris",
    age: 22,
    gender: "Male",
    address: "2121 Redwood St",
    city: "Hilltop",
    state: "NV",
    zip: "34567",
    phone: "555-5678",
    email: "victor.harris@example.com",
    course: "Physics",
    year: "Senior",
    gpa: 3.6,
    advisor: "Dr. Tin",
    enrolled: true,
    credits: 90,
    minor: "Math",
    clubs: ["Physics Club", "Chess Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 25,
    firstName: "Wendy",
    lastName: "Clark",
    age: 20,
    gender: "Female",
    address: "2222 Cedar St",
    city: "Lakewood",
    state: "CO",
    zip: "45678",
    phone: "555-6789",
    email: "wendy.clark@example.com",
    course: "Environmental Science",
    year: "Sophomore",
    gpa: 3.7,
    advisor: "Dr. Lead",
    enrolled: true,
    credits: 45,
    minor: "Geography",
    clubs: ["Eco Club", "Gardening Club"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 26,
    firstName: "Xander",
    lastName: "Rodriguez",
    age: 19,
    gender: "Male",
    address: "2323 Oak St",
    city: "Middleville",
    state: "FL",
    zip: "56789",
    phone: "555-7890",
    email: "xander.rodriguez@example.com",
    course: "Economics",
    year: "Freshman",
    gpa: 3.6,
    advisor: "Dr. Zinc",
    enrolled: true,
    credits: 20,
    minor: "Political Science",
    clubs: ["Economics Club", "Debate Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 27,
    firstName: "Yara",
    lastName: "Martinez",
    age: 21,
    gender: "Female",
    address: "2424 Birch St",
    city: "Valleytown",
    state: "TX",
    zip: "67890",
    phone: "555-8901",
    email: "yara.martinez@example.com",
    course: "Biology",
    year: "Junior",
    gpa: 3.8,
    advisor: "Dr. Iron",
    enrolled: true,
    credits: 70,
    minor: "Chemistry",
    clubs: ["Biology Club", "Swim Team"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 28,
    firstName: "Zach",
    lastName: "White",
    age: 22,
    gender: "Male",
    address: "2525 Poplar St",
    city: "Hightown",
    state: "WA",
    zip: "78901",
    phone: "555-9012",
    email: "zach.white@example.com",
    course: "History",
    year: "Senior",
    gpa: 3.4,
    advisor: "Dr. Steel",
    enrolled: true,
    credits: 85,
    minor: "Political Science",
    clubs: ["History Club", "Debate Team"],
    scholarship: true,
    partTime: true,
  },
  {
    id: 29,
    firstName: "Abby",
    lastName: "Johnson",
    age: 20,
    gender: "Female",
    address: "2626 Maple St",
    city: "Centerville",
    state: "NY",
    zip: "89012",
    phone: "555-0123",
    email: "abby.johnson@example.com",
    course: "English",
    year: "Sophomore",
    gpa: 3.9,
    advisor: "Dr. Tin",
    enrolled: true,
    credits: 45,
    minor: "Creative Writing",
    clubs: ["Literature Club", "Drama Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 30,
    firstName: "Brian",
    lastName: "Taylor",
    age: 21,
    gender: "Male",
    address: "2727 Elm St",
    city: "Eastville",
    state: "IL",
    zip: "90123",
    phone: "555-1234",
    email: "brian.taylor@example.com",
    course: "Political Science",
    year: "Junior",
    gpa: 3.6,
    advisor: "Dr. Lead",
    enrolled: true,
    credits: 60,
    minor: "History",
    clubs: ["Debate Club", "Model UN"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 31,
    firstName: "Chloe",
    lastName: "Anderson",
    age: 22,
    gender: "Female",
    address: "2828 Birch St",
    city: "Westfield",
    state: "CA",
    zip: "01234",
    phone: "555-2345",
    email: "chloe.anderson@example.com",
    course: "Mathematics",
    year: "Senior",
    gpa: 3.5,
    advisor: "Dr. Silver",
    enrolled: true,
    credits: 90,
    minor: "Statistics",
    clubs: ["Math Club", "Tennis Team"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 32,
    firstName: "Daniel",
    lastName: "Thomas",
    age: 19,
    gender: "Male",
    address: "2929 Oak St",
    city: "Southtown",
    state: "NJ",
    zip: "12345",
    phone: "555-3456",
    email: "daniel.thomas@example.com",
    course: "Engineering",
    year: "Freshman",
    gpa: 3.7,
    advisor: "Dr. Bronze",
    enrolled: true,
    credits: 15,
    minor: "Physics",
    clubs: ["Engineering Club", "Robotics Club"],
    scholarship: false,
    partTime: false,
  },
  {
    id: 33,
    firstName: "Ella",
    lastName: "Moore",
    age: 21,
    gender: "Female",
    address: "3030 Spruce St",
    city: "Uptown",
    state: "OR",
    zip: "23456",
    phone: "555-4567",
    email: "ella.moore@example.com",
    course: "Chemistry",
    year: "Junior",
    gpa: 3.8,
    advisor: "Dr. Copper",
    enrolled: true,
    credits: 60,
    minor: "Biology",
    clubs: ["Chemistry Club", "Swim Team"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 34,
    firstName: "Frank",
    lastName: "Jackson",
    age: 20,
    gender: "Male",
    address: "3131 Walnut St",
    city: "Midcity",
    state: "AZ",
    zip: "34567",
    phone: "555-5678",
    email: "frank.jackson@example.com",
    course: "Business",
    year: "Sophomore",
    gpa: 3.6,
    advisor: "Dr. Iron",
    enrolled: true,
    credits: 45,
    minor: "Economics",
    clubs: ["Business Club", "Basketball Team"],
    scholarship: false,
    partTime: true,
  },
  {
    id: 35,
    firstName: "Grace",
    lastName: "Davis",
    age: 22,
    gender: "Female",
    address: "3232 Maple St",
    city: "Oldtown",
    state: "NV",
    zip: "45678",
    phone: "555-6789",
    email: "grace.davis@example.com",
    course: "Art",
    year: "Senior",
    gpa: 3.9,
    advisor: "Dr. Zinc",
    enrolled: true,
    credits: 105,
    minor: "History",
    clubs: ["Art Club", "Photography Club"],
    scholarship: true,
    partTime: false,
  },
  {
    id: 36,
    firstName: "Henry",
    lastName: "Lopez",
    age: 20,
    gender: "Male",
    address: "3333 Cedar St",
    city: "Springdale",
    state: "TX",
    zip: "56789",
    phone: "555-7890",
    email: "henry.lopez@example.com",
    course: "Physics",
    year: "Sophomore",
    gpa: 3.7,
    advisor: "Dr. Tin",
    enrolled: true,
    credits: 40,
    minor: "Math",
    clubs: ["Physics Club", "Chess Club"],
    scholarship: true,
    partTime: false,
  },
];
